## Ensemble Models
<ul>
<li>Why Ensemble? A combination of non correlated models have been proven to perform better than a single model</li>
<li> I used six models, they were imported below with the score on the leaderboard</li>
<li> The best scoring model scored 0.0411 and the worst scored 0.0480</li>
<li><a href="https://mlwave.com/kaggle-ensembling-guide/"> Ensembling guide</a>
<li> I used sklearn voting classifier to try different weights to apply to the model when ensembling</li>
<li> The final weights were adjusted based on the score of the ensemble on the leaderboard to give a final score of 0.003852</li>

</ul>

In [79]:
#import the libraries
import pandas as pd
import numpy as np

In [80]:
#import the class probabilities csv file we created
sub1 = pd.read_csv("submissionlgbp.csv")   #kfold lgb                    0.0411
sub2 = pd.read_csv("submissionbgdtp.csv")  #kfold BaggedDecisiontree    0.0416
sub3 = pd.read_csv("submissiondtp.csv")  #kfold Decisiontree             0.0480
sub4 = pd.read_csv("submissionmlpp.csv")  #kfold mlp                     0.0422
sub5 = pd.read_csv("submissionadp.csv")  #kfold Adaboost                 0.0453
sub6 = pd.read_csv("submissionlogp.csv")  #logisticregression            0.0467

In [81]:
#check the correlation between the models for each model
labels = sub1.columns[1:].tolist()
for label in labels:
    print(label)
    print(np.corrcoef([sub1[label].rank(pct=True), sub2[label].rank(pct=True), sub3[label].rank(pct=True), 
                       sub4[label].rank(pct=True), sub5[label].rank(pct=True),
                      sub6[label].rank(pct=True)]))

3.1.1
[[1.         0.42987156 0.45531914 0.61767454 0.61674042 0.66634278]
 [0.42987156 1.         0.53758621 0.45544407 0.30276694 0.51024654]
 [0.45531914 0.53758621 1.         0.39674838 0.32861132 0.43103697]
 [0.61767454 0.45544407 0.39674838 1.         0.56571711 0.85924687]
 [0.61674042 0.30276694 0.32861132 0.56571711 1.         0.55275234]
 [0.66634278 0.51024654 0.43103697 0.85924687 0.55275234 1.        ]]
3.1.2
[[1.         0.45985237 0.26306541 0.7878281  0.66027089 0.81395102]
 [0.45985237 1.         0.4141922  0.48072043 0.26889306 0.47340047]
 [0.26306541 0.4141922  1.         0.27910524 0.18651057 0.26616835]
 [0.7878281  0.48072043 0.27910524 1.         0.66436973 0.94266216]
 [0.66027089 0.26889306 0.18651057 0.66436973 1.         0.66286834]
 [0.81395102 0.47340047 0.26616835 0.94266216 0.66286834 1.        ]]
3.2.1
[[1.         0.57632203 0.52098297 0.62113834 0.68917993 0.76629106]
 [0.57632203 1.         0.62024152 0.5272412  0.3430593  0.57999482]
 [0.52098297 0

In [82]:
# ensemble the models
average = sub1.copy()
average.iloc[:,1:] = (sub1.iloc[:,1:] * 0.2 + sub2.iloc[:,1:] * 0.3 + sub3.iloc[:,1:] * 0.19
                     +  sub4.iloc[:,1:] * 0.21 + sub5.iloc[:,1:] * 0.1 + sub6.iloc[:,1:] * 0.16)

In [83]:
ave = np.around(average.iloc[0:]).astype('int')

In [84]:
ave.to_csv('average.csv', index=False)